### ISSUE TITLE
Suggested changes to tx.h

### ISSUE THREAD

**Issue by hway** [keeshux/basic-blockchain-programming#1]
````
void bbp_outpoint_fill(bbp_outpoint_t *outpoint, const char *txid, uint32_t index) {
    bbp_parse_hex(BBP_BIG, outpoint->txid, txid);
    bbp_reverse(outpoint->txid, strlen(txid)/2);
    outpoint->index = bbp_eint32(BBP_LITTLE, index);
}
````

**Comment by hway** [comment]
void bbp_txout_create_p2pkh(bbp_txout_t *txout, const uint64_t value, const char *hash160) {
    char script[52] = { 0 };
    sprintf(script, "76a914%s88ac", hash160);
    txout->script_len = strlen(script);
    txout->value = bbp_eint64(BBP_LITTLE, value);
    txout->script = bbp_alloc_hex(BBP_LITTLE, script, (size_t *)&txout->script_len);
}

**Comment by hway** [comment]
It looks very much like the lines were omited intentionally but you asked for it! :)

**Comment by keeshux** [comment]
Hi, your modification to `bbp_txout_create_p2pkh` is redundant, `script_len` is set as an out by `bbp_alloc_hex`.

**Comment by keeshux** [comment]
Leave `bbp_outpoint_fill` as is, the endian problem lies in `bbp_parse_hex`. See #2.

**Comment by hway** [comment]
The issue may lay in Objective-C runtime, I copypasted th.x as is inside an Obj-C method
I agree it's not the best way to play around with your code

I'm not sure about the whole endianness issue, how much is it applicable. Can you name a single big endian machine for this code to be run on? Some hardware wallet? Arduino?
