### ISSUE TITLE
undefined struct bignum_ts 

### ISSUE THREAD

**Issue by Urquelle** [keeshux/basic-blockchain-programming#4]
Hey,

i was trying to follow your tutorial. i'm on windows 10 using Win32 OpenSSL 64Bit. There i stumbled over the error message saying that bignum_ts is undefined. Turns out that you can't declare a non pointer BIGNUM variable anymore, so you have to go with a pointer `BIGNUM *priv`.

Also `BN_init(BIGNUM*)` doesn't exist anymore, so i had to use `BIGNUM* BN_new(void)`.

cheers

**Comment by keeshux** [comment]
@NoobSaibot pull the latest commits and see if it works for you now. It's possible that `BN_init` is not available to all OpenSSL distributions.

**Comment by keeshux** [comment]
@NoobSaibot see if it works for you now. It's possible that `BN_init` is not available to all OpenSSL distributions.
