### ISSUE TITLE
i use the same content to product tx

### ISSUE THREAD

**Issue by TXien** [keeshux/basic-blockchain-programming#5]
your tx is :

0100000001f3a27f485f9833c8318c490403307fef1397121b5dd8fe70777236e7371c4ef3000000001976a91418ba14b3682295cb05230e31fecb00089240660188acffffffff0100e1f505000000001976a91418ba14b3682295cb05230e31fecb00089240660188ac0000000001000000
my tx is:

0100000001f3a27f485f9833c8318c490403307fef1397121b5dd8fe70777236e7371c4ef30000000000ffffffff0100e1f505000000001976a91418ba14b3682295cb05230e31fecb00089240660188ac00000000

why there are a lot of 1976?

**Comment by keeshux** [comment]
`19` + `76a914` is a common pattern you'll find explained here:

https://davidederosa.com/basic-blockchain-programming/the-first-transaction-part-one/

`0x19` (25): Script length in bytes
`0x76`: `OP_DUP`
`0xa9`: `OP_HASH160`
`0x14` (20): Hash160 length in bytes

This is not an issue, post questions on the blog. Closing.
